### ISSUE TITLE
Skype Groups Chats

### ISSUE THREAD

**Issue by Itsprime** [kacgal/ForgeSkype#1]
[Question] Hello, I'm wondering if you're planning on adding Skype Group Chat support? I've done some research and I found that its not easy to do this due to Microsoft removing the p2p for groups.

**Comment by kacgal** [comment]
Hello Itsprime, it looks like group messaging is fully possible, but with a small drawback. I can't hook into old group chats, a new chat would have to be created after the mod is installed. Maybe that's just the case in my Skype, but I'll see what I can do.

**Comment by kacgal** [comment]
Should be working in release 1.2, please report any bugs if you find any
